# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  application:
    name: admin-backend
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ''
    username: ''
    password: ''

